remote_theme: chainAgnostic/cayman
plugins:
- jekyll-remote-theme
- jekyll-relative-links
title: C.A.S.A.
description: Chain Agnostic Standards Alliance
baseurl: /
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - MEMBERS.md